name: puz
version: 0.1.0.0
synopsis: Crosswords in Haskell!
description: Please see README.md
homepage: "https://github.com/jondistad/puz#readme"
license: BSD3
license-file: LICENSE
author: Jon Distad
maintainer: jon.distad@gmail.com
copyright: 2016 Jon Distad
category: Games

ghc-options: #-threaded -rtsopts -with-rtsopts=-N

default-extensions:
  - NoImplicitPrelude

dependencies:
  - base
  - base-prelude
  - binary
  - mtl
  - mtl-prelude
  
library:
  source-dirs: src/

executables:
  puz-exe:
    source-dirs: app/
    main: Main.hs
    dependencies: puz

tests:
  puz-test:
    source-dirs: test/
    main: Spec.hs
    dependencies: puz
