name: hspuz
version: 0.1.0.0
synopsis: Crosswords in Haskell!
description: Please see README.md
homepage: "https://github.com/jondistad/hspuz#readme"
license: BSD3
license-file: LICENSE
author: Jon Distad
maintainer: jon.distad@gmail.com
copyright: 2016 Jon Distad
category: Games
ghc-options: #-threaded -rtsopts -with-rtsopts=-N

dependencies:
  - base

library:
  source-dirs: src/

executables:
  hspuz-exe:
    source-dirs: app/
    main: Main.hs
    dependencies: hspuz

test:
  hspuz-test:
    source-dirs: test/
    main: Spec.hs
    dependencies: hspuz
